<?php

    function z_follow_networks_alter(&$networks, $uid = 0) {

        $networks[$uid]['drupal'] = array(
            'title' => t('Drupal'),
            'domain' => 'drupal.org',
        );

        $networks[$uid]['imdb'] = array(
            'title' => t('IMDB'),
            'domain' => 'imdb.com',
        );

        // $networks[$uid]['Bojana\'s GitHub'] = array(
        //     'title' => t("GitHub"),
        //     'domain' => 'https://github.com/BabaYaga64',
        // );
    }



    // drupal_add_css(drupal_get_path('module', 'custom') . 'sites/css/custom.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
